# Generated by Django 4.2.6 on 2023-10-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teammates_created_teams_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammates',
            name='team',
            field=models.ForeignKey(db_column='team_name', on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
    ]
